name: ottaa_object_detector
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.3.1
  get_it: ^7.2.0
  ottaa_ui_kit:
    git:
      url: https://github.com/OTTAA-Project/OTTAA_flutter_theme.git
      ref: master
  firebase_core: ^2.7.1
  firebase_ml_model_downloader: ^0.2.0+12
  camera: ^0.10.3+2
  image_picker: ^0.8.7
  image: ^4.0.15
  path_provider: ^2.0.13
  tflite: ^1.1.2
  lecle_downloads_path_provider: ^0.0.2+8
  permission: ^0.1.7
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/