name: ottaa_object_detector
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.3
  get_it: ^7.2.0
  ottaa_ui_kit:
    git:
      url: https://github.com/OTTAA-Project/OTTAA_flutter_theme.git
      ref: master
  firebase_core: ^2.4.1
  firebase_ml_model_downloader: ^0.2.0+7
  camera: ^0.10.1
  image_picker: ^0.8.6
  image: ^3.3.0
  path_provider: ^2.0.11
  google_mlkit_object_detection: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/